# -*- coding: utf-8 -*-
"""E-Commerce Sales Data Pipeline and Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbPUG9Kf5Ml8cJv6vv9_TuIZbKGJ7f_m
"""

import pandas as pd
import sqlite3
from datetime import datetime

def load_data(file_path):
    data = pd.read_csv(file_path)
    print("Data Loaded Successfully!")
    return data

sales_data = load_data('/content/sales_data.csv')

def calculate_revenue(data):
    data['Revenue'] = data['Quantity'] * data['Price']
    return data

sales_data = calculate_revenue(sales_data)

def format_date(data):
    data['Date'] = pd.to_datetime(data['Date'], format='%d-%m-%Y')
    return data

sales_data = format_date(sales_data)

def clean_data(data):
    data = data.dropna()
    return data

sales_data = clean_data(sales_data)

def create_database(db_name):
    conn = sqlite3.connect(db_name)
    print(f"Database {db_name} created!")
    return conn

conn = create_database('ecommerce_sales.db')

def load_to_database(data, conn):
    data.to_sql('Sales', conn, if_exists='replace', index=False)
    print("Data loaded into database successfully!")

load_to_database(sales_data, conn)

def get_total_sales(conn):
    query = "SELECT SUM(Revenue) AS Total_Sales FROM Sales"
    total_sales = pd.read_sql(query, conn)
    return total_sales

total_sales = get_total_sales(conn)
print("Total Sales Revenue:", total_sales.iloc[0]['Total_Sales'])

