# -*- coding: utf-8 -*-
"""Superstore analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pzgTQwkA0HkbmueDbWQvncCV2EQXeELB
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Superstore.csv",encoding='ISO8859-1')
df.head()

print(f"Shape of dataset:{df.shape}")

print(f"Missing values:{df.isnull().sum()}")

df.drop_duplicates(inplace=True)
print(f"Shape of dataset after removing duplicates:{df.shape}")

print("Dataset info:")
print(df.info())

print("Data types:")
print(df.dtypes)

print("Summary statistics:")
print(df.describe)

total_sales=df['Sales'].sum()
total_profit=df['Profit'].sum()
print(f"Total sales:{total_sales}")
print(f"Total profit:{total_profit}")

top_states=df.groupby('State')['Profit'].sum().sort_values(ascending=False).head(10)
print(f"Top profitable states:{top_states}")

plt.figure(figsize=(8,5))
sns.barplot(data=df,x="Category",y="Sales",estimator=sum)
plt.title("Total sales by category")
plt.ylabel('Sales')
plt.show()

region_profit=df.groupby('Region')['Profit'].sum()
print(f"Profit by region:{region_profit}")

plt.figure(figsize=(8,5))
sns.barplot(data=df,x="Region",y="Profit")
plt.title("Total profit by region")
plt.show()

corr = df[['Sales', 'Quantity', 'Discount', 'Profit']].corr()

plt.figure(figsize=(6, 4))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

with open("superstore_insights.txt", "w") as file:
    file.write("🔍 Superstore Sales Analysis Summary:\n")
    file.write(f"Total Sales: ${total_sales:,.2f}\n")
    file.write(f"Total Profit: ${total_profit:,.2f}\n\n")
    file.write("Top 10 Profitable States:\n")
    file.write(top_states.to_string())
    file.write("\n\nDiscount negatively impacts profit.\n")
    file.write("Technology is often more profitable than Furniture.\n")

print("\n✅ Analysis Complete. Insights saved to 'superstore_insights.txt'.")

